	"<head>\n"
		"<meta charset='utf-8'/>\n"
		"<title>REDMOND</title>\n"
		"<style>\n"
			"html, body\n"
			"{\n"
				"height: 80%;\n"
				"margin: 0;\n"
			"}\n"
			".enterIPaddr\n"
			"{\n"
				"margin: auto;\n"
				"text-align: center;\n"
			"}\n"
			".centerButtons\n"
			"{\n"
				"border: 10px solid darkred;\n"
				"max-width: 100%;\n"
				"height: 50vh;\n"
				"margin: auto;\n"
				"display: flex;\n"
				"align-items: center;\n"
				"justify-content: center;\n"
				"background: linear-gradient(45deg, rgb(51,51,51), darkgray);\n"
			"}\n"
			"#debugPress\n"
			"{\n"
				"border: 10px solid gray;\n"
				"max-width: 900px;\n"
				"height: 10vh;\n"
				"margin: auto;\n"
				"display: flex;\n"
				"align-items: center;\n"
				"justify-content: center;\n"
			"}\n"
			"#debugRX\n"
			"{\n"
				"border: 10px solid gray;\n"
				"max-width: 900px;\n"
				"height: 10vh;\n"
				"margin: auto;\n"
				"display: flex;\n"
				"align-items: center;\n"
				"justify-content: center;\n"
			"}\n"
			"#extButtons\n"
			"{\n"
				"margin: auto;\n"
				"display: flex;\n"
				"align-items: center;\n"
				"justify-content: center;\n"
				"border-radius: 50%;\n"
				"width: 10em;\n"
				"height: 10em;\n"
				"font-weight: bold;\n"
				"font-size: 200%;\n"
				"border: 2px solid red;\n"
				"margin: auto;\n"
				"box-shadow: inset -20px 20px 20px rgba(0,0,0,.2), inset -20px 20px 20px rgba(0,0,0,.8);\n"
			"}\n"
			"#innButtons\n"
			"{\n"
				"border-radius: 50%;\n"
				"width: 70%;\n"
				"height: 70%;\n"
				"margin: auto;\n"
				"display: flex;\n"
				"align-items: center;\n"
				"justify-content: center;\n"
			"}\n"
			".classButtonRecipes\n"
			"{\n"
				"background: blue;\n"
			"}\n"
			".classButtonFastRun\n"
			"{\n"
				"background: blue;\n"
			"}\n"
			".classButtonProgs\n"
			"{\n"
				"background: blue;\n"
			"}\n"
			".innerButtonRecipes\n"
			"{\n"
				"color: orange;\n"
				"background: green;\n"
			"}\n"
			".innerButtonFastRun\n"
			"{\n"
				"color: orange;\n"
				"background: green;\n"
			"}\n"
			".innerButtonProgs\n"
			"{\n"
				"color: orange;\n"
				"background: green;\n"
			"}\n"
		"</style>\n"
	"</head>\n"